#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

eval $(gnome-keyring-daemon --start --components=pkcs11,ssh,secrets)
lxpolkit &
udiskie &
sxhkd &
xset s 600 120
xss-lock -n dim-screen.sh -- /home/m2/.local/bin/betterlockscreen -s blur &
rclone -v mount GoogleDrive: ~/GoogleDrive/ --vfs-cache-mode writes --daemon &
~/.fehbg &
picom --experimental-backends -b
systemctl --user restart spotifyd.service
unclutter &
run_ccursereminders.py 30 &

exec i3
